apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample_app
  labels:
    app: sample_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample_app
  template:
    metadata:
      labels:
        app: sample_app
    spec:
      containers:
      - name: sample_app
        image: lsall1071/sample_app:1.0.0
        ports:
        - containerPort: 80
